#!/usr/bin/env python3
# The sequence of triangle numbers is generated by adding the natural numbers.
# The 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28
# What is the value of the first triangle number to have over
#   five hundred divisors?
# Answer:  76576500

import math

divisor_count = 0
trinum = 0
i = 1
while True:
	trinum += i
	divisor_count = 1
	for j in range(2, math.ceil(trinum**0.5)):
		if trinum % j == 0:
			divisor_count += 2
	i += 1
	if divisor_count >= 500:
		break

print(trinum)
