/* Project Euler #29
 * How many distinct terms are in the sequence generated by a^b for
 *   2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 * Answer:    9183
*/

#include <iostream>
#include <math.h>
#include <set>
using namespace std;

int main()
{
	set<double> s;

	for (int a = 2; a <= 100; a++)
		for (int b = 2; b <= 100; b++)
			s.insert(pow(a,b));

	cout << s.size() << endl;

	return 0;
}

