/* Project Euler #11
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * The 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28
 * What is the value of the first triangle number to have over
 *   five hundred divisors?
 * Answer:  76576500
*/

#include <iostream>
#include <math.h>

int main()
{
	int divisor_count = 0;
	int trinum = 0;
	for (int i = 1; divisor_count <= 500; i++)
	{
		trinum += i;
		divisor_count = 1;
		int z = (int)(sqrt(trinum));
		for (int j = 2; j <= z; j++)
			if (trinum % j == 0)
				divisor_count += 2;
	}
	std::cout << trinum << std::endl;
	return 0;
}

