// Euler012.prg
// The sequence of triangle numbers is generated by adding the natural numbers.
// The 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28
// What is the value of the first triangle number to have over
//   five hundred divisors?
// Answer:  76576500

CLASS Euler012

	STATIC METHOD Run() AS INT
		LOCAL i := 1, trinum := 0, limit := 500 AS INT

		WHILE TRUE
			trinum += i
			IF NumberOfDivisors(trinum) > limit
				EXIT
			ENDIF
			i++
		ENDDO

		RETURN trinum

	STATIC METHOD NumberOfDivisors(n AS INT) AS INT
		LOCAL count := 2, z := FLOOR(SQRT(n)), i AS INT

		FOR i := 2 UPTO z
			IF n % i == 0
				count += 2
			ENDIF
		NEXT

		RETURN count

END CLASS
